# Generated by Django 5.0.1 on 2024-02-05 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MyUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=128)),
                ('chat_id', models.CharField(max_length=120, unique=True)),
                ('phone_number', models.CharField(max_length=12, unique=True)),
            ],
        ),
    ]
